SM6_GTX1080:
  name: GTX 1080
  path: ./SM6_GTX1080
  spec:
    # sm_count: 28
    sm_count: 20
    # clock_speed: 1481
    clock_speed: 1607
  
SM86_RTX3070:
  name: RTX 3070
  path: ./SM86_RTX3070
  spec:
    sm_count: 46
    # thats what gpgpusim says (internet says 1500 (1725 boost)
    clock_speed: 1132

SM86_A6000:
  name: A6000
  path: ./SM86_A6000
  spec:
    sm_count: 84
    clock_speed: 1410
