name: containers

on: [push, pull_request]

jobs:
  build:
    name: test ${{ matrix.simulator.name }} container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        simulator:
          # native and sass require a physical GPU device
          - name: native
            bench: false
          - name: accelsim-sass
            bench: false
          - name: accelsim-ptx
            bench: true
          - name: tejas
            bench: true
          - name: m2s
            bench: true
          - name: macsim
            bench: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      # - name: Add musl target toolchain
      #   run: rustup target add x86_64-unknown-linux-musl
      # - name: Compile tools
      #   run: >-
      #     cargo build
      #     --release
      #     --all-targets
      #     --target x86_64-unknown-linux-musl
 
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev --system
      
      - name: Build ${{ matrix.simulator.name }} container
        run: >-
          inv build
          -s ${{ matrix.simulator.name }}
          --base

      - name: Benchmark ${{ matrix.simulator.name }}
        if: ${{ matrix.simulator.bench }}
        run: >-
          inv bench
          -s ${{ matrix.simulator.name }}
          --timeout-mins 40
          --local
