name: containers

on: [push, pull_request]

jobs:
  build:
    name: build ${{ matrix.simulator }} container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        simulator:
          - native
          - accelsim-sass
          - accelsim-ptx
          - tejas
          - m2s
          - macsim

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      # - name: Add musl target toolchain
      #   run: rustup target add x86_64-unknown-linux-musl
      # - name: Compile tools
      #   run: >-
      #     cargo build
      #     --release
      #     --all-targets
      #     --target x86_64-unknown-linux-musl
 
      # - name: Install dependencies
      #   run: |
      #     pip install pipenv
      #     pipenv install --dev --system
      
      - name: Build container
        run: >-
          inv build
          -s ${{ matrix.simulator }}
          --base
