name: test

on: [push, pull_request]

jobs:
  test-parsers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Add musl target toolchain
        run: rustup target add x86_64-unknown-linux-musl

      - name: Test
        run: >-
          cargo test
          --target x86_64-unknown-linux-musl
          --all-targets

  test-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev --system

      - name: Lint
        run: flake8 gpusims/

      - name: Test
        run: python -m unittest tests/*
