name: test

on: [push, pull_request]

jobs:
  test-parsers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test
        run: >-
          cargo test
          --all-targets

  test-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pipenv install --dev --system

      - name: Test
        run: |
          python -m unittest tests/*
